Unit Conversion Program

In [ ]:
def conv():
    print("1 length")
    print("2 weight")
    print("3 volume")

    c = input("type: ")

    try:
        v = float(input("value: "))

        if c == "1":
            o = input("1 m-ft 2 ft-m: ")
            if o == "1":
                print(v*3.28084)
            else:
                print(v/3.28084)

        elif c == "2":
            o = input("1 kg-lb 2 lb-kg: ")
            if o == "1":
                print(v*2.20462)
            else:
                print(v/2.20462)

        elif c == "3":
            o = input("1 L-gal 2 gal-L: ")
            if o == "1":
                print(v*0.264172)
            else:
                print(v/0.264172)

    except:
        print("err")

conv()

1 length
2 weight
3 volume
type: 1
value: 100
1 m-ft 2 ft-m: 2
30.47999902464003


Mathematical Operations on List

In [ ]:
def s(l):
  return sum(l)
def a(l):
  return sum(l)/len(l)
def mx(l):
  return max(l)
def mn(l):
  return min(l)

try:
    l = list(map(float,input("nums: ").split()))
    o = input("1 sum 2 avg 3 max 4 min: ")

    if o=="1":
        print(s(l))
    elif o=="2":
        print(a(l))
    elif o=="3":
        print(mx(l))
    elif o=="4":
        print(mn(l))

except:
    print("err")

nums: 20 10 
1 sum 2 avg 3 max 4 min: 1
30.0


In [ ]:
#list manipulation
#every other
def eo(l):
    return l[::2]

l=[1,2,3,4,5,6]
print("input:",l)
print("output:",eo(l))

input: [1, 2, 3, 4, 5, 6]
output: [1, 3, 5]


In [ ]:
#slice
def sub(l,s,e):
    return l[s:e+1]

l=[1,2,3,4,5,6]
print("input:",l)
print("output:",sub(l,2,4))

input: [1, 2, 3, 4, 5, 6]
output: [3, 4, 5]


In [ ]:
#reverse list
def rev(l):
    return l[::-1]

l=[1,2,3,4,5]
print("input:",l)
print("output:",rev(l))

input: [1, 2, 3, 4, 5]
output: [5, 4, 3, 2, 1]


In [ ]:
# remove first and last
def rm(l):
    return l[1:-1]

l=[1,2,3,4,5]
print("input:",l)
print("output:",rm(l))

input: [1, 2, 3, 4, 5]
output: [2, 3, 4]


In [ ]:
#get first n elements
def fn(l,n):
    return l[:n]

l=[1,2,3,4,5]
print("input:",l)
print("output:",fn(l,3))

input: [1, 2, 3, 4, 5]
output: [1, 2, 3]


In [ ]:
#get last n
def ln(l,n):
    return l[-n:]

l=[1,2,3,4,5]
print("input:",l)
print("output:",ln(l,2))

input: [1, 2, 3, 4, 5]
output: [4, 5]


In [ ]:
#reverse skip
def rs(l):
    return l[-2::-2]

l=[1,2,3,4,5,6]
print("input:",l)
print("output:",rs(l))

input: [1, 2, 3, 4, 5, 6]
output: [5, 3, 1]


In [ ]:
#flatten a nested list
def flat(l):
    r=[]
    for i in l:
        r+=i
    return r

l=[[1,2],[3,4],[5]]
print("input:",l)
print("output:",flat(l))

input: [[1, 2], [3, 4], [5]]
output: [1, 2, 3, 4, 5]


In [ ]:
#access nested element
def acc(l,idx):
    x=l
    for i in idx:
        x=x[i]
    return x

l=[[1,2,3],[4,5,6],[7,8,9]]
i=[1,2]

print("input:",l)
print("indices:",i)
print("output:",acc(l,i))

input: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices: [1, 2]
output: 6


In [ ]:
#sum of nested list
def sn(l):
    t=0
    for i in l:
        if type(i)==list:
            t+=sn(i)
        else:
            t+=i
    return t

l=[[1,2],[3,[4,5]],6]

print("input:",l)
print("output:",sn(l))

input: [[1, 2], [3, [4, 5]], 6]
output: 21


In [ ]:
#remove specific element
def rem(l,e):
    r=[]
    for i in l:
        if type(i)==list:
            r.append(rem(i,e))
        elif i!=e:
            r.append(i)
    return r

l=[[1,2],[3,2],[4,5]]

print("input:",l)
print("remove:",2)
print("output:",rem(l,2))

input: [[1, 2], [3, 2], [4, 5]]
remove: 2
output: [[1], [3], [4, 5]]


In [ ]:
#find max in nested list
def fm(l):
    m=-999999
    for i in l:
        if type(i)==list:
            m=max(m,fm(i))
        else:
            m=max(m,i)
    return m

l=[[1,2],[3,[4,5]],6]

print("input:",l)
print("output:",fm(l))

input: [[1, 2], [3, [4, 5]], 6]
output: 6


In [ ]:
#count occurences
def co(l,e):
    c=0
    for i in l:
        if type(i)==list:
            c+=co(i,e)
        elif i==e:
            c+=1
    return c

l=[[1,2],[2,3],[2,4]]

print("input:",l)
print("count:",2)
print("output:",co(l,2))

input: [[1, 2], [2, 3], [2, 4]]
count: 2
output: 3


In [ ]:
#deep flatten
def df(l):
    r=[]
    for i in l:
        if type(i)==list:
            r+=df(i)
        else:
            r.append(i)
    return r

l=[[[1,2],[3,4]],[[5,6],[7,8]]]

print("input:",l)
print("output:",df(l))

input: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
#average of nested list
def df(l):
    r=[]
    for i in l:
        if type(i)==list:
            r+=df(i)
        else:
            r.append(i)
    return r

def avg(l):
    f=df(l)
    return sum(f)/len(f)

l=[[1,2],[3,4],[5,6]]

print("input:",l)
print("output:",avg(l))

input: [[1, 2], [3, 4], [5, 6]]
output: 3.5


Numpy exercises


In [ ]:
import numpy as np


In [ ]:
#basic vector and matrix operation

#1
a=np.empty((2,2))
print("1\n",a)

#2
b=np.ones((4,2))
print("2\n",b)

#3
c=np.full((3,3),7)
print("3\n",c)

#4
d=np.array([[1,2,3],[4,5,6]])
z=np.zeros_like(d)
print("4\n",z)

#5
o=np.ones_like(d)
print("5\n",o)

#6
new_list=[1,2,3,4]
arr=np.array(new_list)
print("6\n",arr)

1
 [[2.13198979e-315 0.00000000e+000]
 [5.90408447e-321 1.76262290e-312]]
2
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
4
 [[0 0 0]
 [0 0 0]]
5
 [[1 1 1]
 [1 1 1]]
6
 [1 2 3 4]


In [ ]:
#array manipulation : numerical ranges and indexing

#1
a=np.arange(10,50)
print("1\n",a)

#2
b=np.arange(9).reshape(3,3)
print("2\n",b)

#3
c=np.eye(3)
print("3\n",c)

#4
d=np.random.random(30)
print("4\n",d)
print("mean =",d.mean())

#5
e=np.random.random((10,10))
print("5\n",e)
print("min =",e.min())
print("max =",e.max())

#6
f=np.zeros(10)
f[4]=1
print("6\n",f)

#7
arr=np.array([1,2,0,0,4,0])
print("7\n",arr[::-1])

#8
g=np.ones((5,5))
g[1:-1,1:-1]=0
print("8\n",g)

#9
h=np.zeros((8,8),dtype=int)
h[1::2,::2]=1
h[::2,1::2]=1
print("9\n",h)


1
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4
 [0.60493869 0.57305684 0.31158584 0.10518579 0.30407606 0.16351639
 0.96533848 0.51255346 0.19210985 0.0986304  0.95085681 0.83672636
 0.89645644 0.5992659  0.57145696 0.61678453 0.1825743  0.90167704
 0.68573888 0.0178055  0.93010018 0.03603883 0.31344456 0.71899631
 0.93746135 0.41039598 0.1330375  0.3870748  0.69981367 0.43786738]
mean = 0.5031521694542679
5
 [[0.33321748 0.61438883 0.15578786 0.92128671 0.8472226  0.48630982
  0.14306419 0.07269503 0.2421246  0.62891626]
 [0.93399873 0.18025994 0.94901577 0.49942583 0.53748435 0.47920296
  0.76823353 0.70267381 0.60729368 0.90945664]
 [0.19178755 0.56778932 0.95950911 0.47700235 0.932144   0.7883247
  0.51950705 0.22920902 0.40562318 0.22161402]
 [0.94585595 0.7291493  0.95360738 0.08492809 0.92374596 0.72177852
  0.56329753 0.61194588

In [ ]:
#array operations

x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])

#1 add
print("1 add\n",x+y)

#2 subtract
print("2 subtract\n",x-y)

#3 multiply with integers
print("3 multiply\n",x*2)
print(y*3)

#4 square
print("4 square\n",x**2)
print(y**2)

#5 dot products
print("5 dot v,w =",np.dot(v,w))
print("dot x,v =",np.dot(x,v))
print("dot x,y\n",np.dot(x,y))

#6 concatenate
print("6 concat x,y row\n",np.concatenate((x,y),axis=0))
print("concat v,w column\n",np.column_stack((v,w)))

#7 concatenate x and v
print("7 concat x,v")
try:
    print(np.concatenate((x,v),axis=0))
except Exception as e:
    print("error:",e)


1 add
 [[ 6  8]
 [10 13]]
2 subtract
 [[-4 -4]
 [-4 -3]]
3 multiply
 [[ 2  4]
 [ 6 10]]
[[15 18]
 [21 24]]
4 square
 [[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
5 dot v,w = 219
dot x,v = [29 77]
dot x,y
 [[19 22]
 [50 58]]
6 concat x,y row
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
concat v,w column
 [[ 9 11]
 [10 12]]
7 concat x,v
error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


for 2.7 there's error because Numpy cannot concatenate arrays with different dimensions, so it throws a dimension mismatch error.


In [ ]:
#matrix operations
#Prove A.A−1 = I.

A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

ai=np.linalg.inv(A)
i=np.dot(A,ai)

print("A inverse =\n",ai)
print("A.A^-1 =\n",i)

#Prove AB ̸= BA.
A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

ab=np.dot(A,B)
ba=np.dot(B,A)

print("AB =\n",ab)
print("BA =\n",ba)
print("AB != BA =",not np.array_equal(ab,ba))

#Prove (AB)^T = B^T.A^T
A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

ab=np.dot(A,B)

l=ab.T
r=np.dot(B.T,A.T)

print("(AB)^T =\n",l)
print("B^T A^T =\n",r)
print("equal =",np.array_equal(l,r))



A inverse =
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A.A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB != BA = True
(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
equal = True


In [ ]:
#Solve the following system of Linear equation using Inverse Methods.
#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9


A=np.array([[2,-3,1],
            [1,-1,2],
            [3,1,-1]])

B=np.array([[-1],
            [-3],
            [9]])

print("A =\n",A)
print("B =\n",B)

#find inverse of A
ai=np.linalg.inv(A)
print("A inverse=\n",ai)

#X = A^-1 B
X=np.dot(ai,B)

print("solution X=\n",X)

A =
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
B =
 [[-1]
 [-3]
 [ 9]]
A inverse=
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
solution X=
 [[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
A=np.array([[2,-3,1],
            [1,-1,2],
            [3,1,-1]])

B=np.array([[-1],
            [-3],
            [9]])

#direct solution
X=np.linalg.inv(A)@B

print("solution=\n",X)

solution=
 [[ 2.]
 [ 1.]
 [-2.]]


"how fast is numpy" experiment exercises

In [ ]:
import time

In [ ]:
#element wise addition

n=1000000
a=list(range(n))
b=list(range(n))

s=time.time()

c=[a[i]+b[i] for i in range(n)]

e=time.time()

print("python list addition time =",e-s)

a=np.arange(n)
b=np.arange(n)

c=a+b

e=time.time()

print("numpy addition time =",e-s)

python list addition time = 0.0734257698059082
numpy addition time = 0.09894084930419922


In [ ]:
#element wise multiplication
n=1000000
a=np.arange(n)
b=np.arange(n)

s=time.time()

c=a+b

e=time.time()

print("numpy addition time =",e-s)
a=list(range(n))
b=list(range(n))

c=[a[i]*b[i] for i in range(n)]

e=time.time()

print("python list multiplication time =",e-s)

numpy addition time = 0.0007009506225585938
python list multiplication time = 0.1086115837097168


In [ ]:
#Dot product
n=1000000
a=list(range(n))
b=list(range(n))

s=time.time()

dot=0
for i in range(n):
    dot+=a[i]*b[i]

e=time.time()

print("python dot product =",dot)
print("time =",e-s)

a=np.arange(n)
b=np.arange(n)

s_np=time.time()

dot=np.dot(a,b)

e_np=time.time()

print("numpy dot product =",dot)
print("time =",e_np-s_np)

python dot product = 333332833333500000
time = 0.13704299926757812
numpy dot product = 333332833333500000
time = 0.0007905960083007812


In [ ]:
#matrix multiplication
#python lists

n=1000

A=[[1]*n for _ in range(n)]
B=[[1]*n for _ in range(n)]
C=[[0]*n for _ in range(n)]

s=time.time()

for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i][j]+=A[i][k]*B[k][j]

e=time.time()

print("python matrix mult time =",e-s)

In [ ]:
#numpy matrix multi
n=1000

A=np.ones((n,n))
B=np.ones((n,n))

s=time.time()

C=np.dot(A,B)

e=time.time()

print("numpy matrix mult time =",e-s)